// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCACrrN34Txs1V0azjVEpUvxlpLxB_l3wY',
    appId: '1:132895213768:web:e95b6d6019366327e2bdfd',
    messagingSenderId: '132895213768',
    projectId: 'cheez-bro',
    authDomain: 'cheez-bro.firebaseapp.com',
    storageBucket: 'cheez-bro.firebasestorage.app',
    measurementId: 'G-9F8P04J5RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYyiyzSCxK4HquYIzt37Txl7bsOcgqdOU',
    appId: '1:132895213768:android:b13921da43356954e2bdfd',
    messagingSenderId: '132895213768',
    projectId: 'cheez-bro',
    storageBucket: 'cheez-bro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6CW_bsyQws9awgTo03RSLkZXRcpb8zLA',
    appId: '1:132895213768:ios:ee64d8680466a3fee2bdfd',
    messagingSenderId: '132895213768',
    projectId: 'cheez-bro',
    storageBucket: 'cheez-bro.firebasestorage.app',
    iosBundleId: 'com.example.cheezBro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6CW_bsyQws9awgTo03RSLkZXRcpb8zLA',
    appId: '1:132895213768:ios:ee64d8680466a3fee2bdfd',
    messagingSenderId: '132895213768',
    projectId: 'cheez-bro',
    storageBucket: 'cheez-bro.firebasestorage.app',
    iosBundleId: 'com.example.cheezBro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCACrrN34Txs1V0azjVEpUvxlpLxB_l3wY',
    appId: '1:132895213768:web:489f7a4511d4c95ae2bdfd',
    messagingSenderId: '132895213768',
    projectId: 'cheez-bro',
    authDomain: 'cheez-bro.firebaseapp.com',
    storageBucket: 'cheez-bro.firebasestorage.app',
    measurementId: 'G-N6W6XT1DHH',
  );
}
